version: '3.4'
services:
  db:
    image: postgres:11
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /home/fileserver/urls/db:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    restart: always
    env_file: .env
    entrypoint: ["./start.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations

  redis:
      image: redis:latest

  worker:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    env_file: .env
    command: celery -A celery worker --loglevel=info
    depends_on:
      - redis