version: '3.4'
services:
  db:
    image: postgres:11
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /home/fileserver/urls/db:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    restart: always
    env_file: .env
    command: python src/main.py run -h 0.0.0.0 -p 8000
    entrypoint: ["./start.sh"]
#    command: gunicorn --bind 0.0.0.0:8000 src.main:app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations

  redis:
      image: redis:latest

  worker:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    env_file: .env
    working_dir: /app/src
    command: celery -A main.celery worker --loglevel=info -B
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations