"""empty message

Revision ID: f65df0b8aeb8
Revises: 4400e534a67b
Create Date: 2021-02-06 09:42:08.215125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65df0b8aeb8'
down_revision = '4400e534a67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'urls', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='unique')
    # ### end Alembic commands ###
